 export const cardData = [
    {
      id: 1,
      title: "ONE WAY TRIP",
      paymentMethod: "Paid by Cash",
      description: "Graph.js:157:22 error during build process",
      location: "Hyderabad",
    },
    {
      id: 2,
      title: "Card 2",
      paymentMethod: "Paid by UPI",
      description: "Metro bundler failed due to timeout",
      location: "Bangalore",
    },
    {
      id: 3,
      title: "Card 3",
      paymentMethod: "Paid by Card",
      description: "React Native version mismatch error",
      location: "Chennai",
    },
    {
      id: 4,
      title: "Card 4",
      paymentMethod: "Paid by Cash",
      description: "Redux state not updating properly",
      location: "Delhi",
    },
    {
      id: 5,
      title: "Card 5",
      paymentMethod: "Paid by UPI",
      description: "Navigation not working on Android",
      location: "Pune",
    },
    {
      id: 6,
      title: "Card 6",
      paymentMethod: "Paid by Card",
      description: "iOS build failing due to provisioning",
      location: "Mumbai",
    },
    {
      id: 7,
      title: "Card 7",
      paymentMethod: "Paid by Cash",
      description: "App crashing randomly after login",
      location: "Kolkata",
    },
    {
      id: 8,
      title: "Card 8",
      paymentMethod: "Paid by UPI",
      description: "Camera permission issue on Android",
      location: "Ahmedabad",
    },
    {
      id: 9,
      title: "Card 9",
      paymentMethod: "Paid by Card",
      description: "App stuck on splash screen",
      location: "Noida",
    },
    {
      id: 10,
      title: "Card 10",
      paymentMethod: "Paid by Cash",
      description: "Dark mode not applying styles",
      location: "Jaipur",
    },
  ];